version: "3.8"

services:
  web:
    build: .
    container_name: apache_server
    ports:
      - "3000:80"                     # web trực tiếp (bỏ qua WAF/proxy)
    volumes:
      - ./public:/var/www/html:rw
      - ./logs/apache2:/var/log/apache2   # <-- Apache logs (access.log, error.log)
      - ./logs/modsecurity:/var/log/modsecurity  # <-- ModSecurity audit logs
      - ./modsecurity/modsecurity.conf:/etc/modsecurity/modsecurity.conf:ro
      - ./modsecurity/unicode.mapping:/etc/modsecurity/unicode.mapping:ro
    environment:
      - DB_HOST=db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "@Root123"
      MYSQL_DATABASE: "students"
      MYSQL_USER: "student"
      MYSQL_PASSWORD: "@Student123"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: student
      PMA_PASSWORD: "@Student123"
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
